  
arch:
  - arm64
os: linux
dist: focal

language: generic

services:
  - docker

before_install:
  - docker build -t moussavdb/runtime-java-arm64:latest -t moussavdb/runtime-java-arm64:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/runtime-java-arm64
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/runtime-java-arm64:latest;
    docker push moussavdb/runtime-java-arm64:build_$TRAVIS_BUILD_NUMBER;
